/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as automation from "./automation";
export type { automation };
import type * as functions from "./functions";
export type { functions };
import type * as shared from "./shared";
export type { shared };
import type * as vendor from "./vendor";
export type { vendor };
import type * as vrf from "./vrf";
export type { vrf };
